name: test_python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Specify exact version for consistency

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest test_myfile.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Upload test results
        if: always()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: test-results
          path: ./junit/test-results.xml
